# Generated by Django 5.2.7 on 2025-10-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_received', models.DateField()),
                ('save_to', models.CharField(choices=[('db', 'Сохранить в базу данных'), ('file', 'Сохранить в файл')], default='db', max_length=4)),
            ],
        ),
    ]
